backend:
  name: git-gateway
  branch: main # Vérifie si ta branche s'appelle main ou master

media_folder: "images/uploads" # Où seront stockées tes photos de projets
public_folder: "/images/uploads"

collections:
  - name: "projets"
    label: "Mes Projets"
    folder: "content/projets" # Les données seront sauvées ici en fichiers JSON
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Titre du Projet", name: "title", widget: "string" }
      - { label: "Thème", name: "theme", widget: "string" }
      - { label: "Catégorie", name: "category", widget: "select", options: ["product", "graphic", "industrial", "craft"] }
      - { label: "Image Principale", name: "image", widget: "image" }
      - { label: "Description", name: "body", widget: "markdown" }